### PR TITLE
Upgrade to version 1.3

### PR DESCRIPTION
**Pull request by jlev**
Hey Courtney, lots of new features here in [v1.3](https://github.com/spacedogXYZ/call-power/releases/tag/v1.3.0).

Let's talk about the upgrade process during our work period tomorrow.

- Josh

### CODE REVIEW

**Comment by jlev** [comment]
Hey @crwallace, when you merge and deploy this you'll need to run `python manager.py migrate up` to insert new tables and columns in the database.

**Comment by bshyong** [comment]
Thanks @jlev are there any other major things we need to be aware of for the upgrade?

**Comment by jlev** [comment]
@bshyong I've also upgraded a lot of the underlying packages to stay up to date there and with Twilio's API. There are also fair number of small bug fixes, testing improvements and a visual design refresh, which looks a bit less bootstrapy.

There are release notes for every point version at https://github.com/spacedogXYZ/call-power/releases

**Comment by jlev** [comment]
I'd also suggest upgrading the base stack, just to keep things up-to-date in the OS level.
`heroku stack:set heroku-16`

If you do want to use the scheduled recurring calls feature, you'll need to run one clock process and at least one worker. These are defined in the procfile, you'll just need to turn them on in the Heroku UI.

Also the OpenStates API now requires a key, which you can register for at https://openstates.org/api/register/ and place into the environment as OPENSTATES_API_KEY

**Pull request merged**
