### PR TITLE
Fixes candidate phone number lookup

### LINKED ISSUE #8: Candidate phone number lookup is broken
When I try to look up elected officials I get no result.

screenshot 2017-08-04 18 28 49

Also, when I test campaigns that previously were set up to use phone data from external sources, I hear, "sorry this campaign is not available in your area." I assume this means no number was found for my zipcode, but I think this is because the app cannot find any political contact data.

### PR DESCRIPTION
**Pull request by crwallace**
fixes #8

### CODE REVIEW

**Review by bshyong — APPROVED** [review]
LGTM don't see anything crazy here

**Comment by jlev** [comment]
FYI you'll need to re-run `python manager.py loadpoliticaldata` after deploying, to update the redis cache

**Comment by bshyong** [comment]
thanks @jlev! @crwallace feel free to merge when ready

**Comment by jlev** [comment]
Looks like a few problems cropped up with the content security policy. I added exclusions for the additional analytics platforms you're using in https://github.com/OpenSourceActivismTech/call-power/commit/3703f512dcfadf9ad417afdae5d1d01735515dd7

**Pull request merged**
